### ISSUE TITLE
 IllegalArgumentException: locale is null when try to load entities metadata

### ISSUE THREAD

**Issue by vadimbasko** [Haulmont/jmix-rest#27]
* run https://github.com/jmix-projects/scr-jmix
* try to fetch `rest/metadata/entities`

AR: 
```
java.lang.IllegalArgumentException: locale is null
    at io.jmix.core.common.util.Preconditions.checkNotNullArgument(Preconditions.java:101) ~[jmix-core-0.2.0-SNAPSHOT.jar:na]
    at io.jmix.core.impl.MessagesImpl.getMessage(MessagesImpl.java:72) ~[jmix-core-0.2.0-SNAPSHOT.jar:na]
    at io.jmix.core.impl.MessagesImpl.getMessage(MessagesImpl.java:65) ~[jmix-core-0.2.0-SNAPSHOT.jar:na]
    at io.jmix.core.MessageTools.getPropertyCaption(MessageTools.java:249) ~[jmix-core-0.2.0-SNAPSHOT.jar:na]
    at io.jmix.core.MessageTools.getPropertyCaption(MessageTools.java:231) ~[jmix-core-0.2.0-SNAPSHOT.jar:na]

```

**Comment by plakhov** [comment]
Can't reproduce
