### ISSUE TITLE
java.lang.IllegalStateException: @Order on WebSecurityConfigurers must be unique

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-rest#87]
**Environment:**
Jmix version: 1.1.0
Jmix Studio plugin version: 1.1.0-211
IntelliJ version: IntelliJ IDEA 2021.1.3 (Ultimate Edition)

**TC:**
1. Open [attached](https://github.com/Haulmont/jmix-rest/files/7433612/sample-sales-jmix.zip) project -> Run app

**AR:**

Application run failed:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration': Injection of autowired dependencies failed; nested exception is java.lang.IllegalStateException: @Order on WebSecurityConfigurers must be unique. Order of 200 was already used on io.jmix.autoconfigure.securityoauth2.SecurityOAuth2AutoConfiguration$Oauth2AuthorizationServerConfiguration@55456711, so it cannot be used on io.jmix.autoconfigure.webdav.WebdavRestAutoConfiguration$DefaultWebdavRestBasicAuthConfiguration$$EnhancerBySpringCGLIB$$b982ced9@38c86702 too.
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:405) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.10.jar:5.3.10]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.10.jar:5.3.10]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.5.5.jar:2.5.5]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) [spring-boot-2.5.5.jar:2.5.5]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) [spring-boot-2.5.5.jar:2.5.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) [spring-boot-2.5.5.jar:2.5.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) [spring-boot-2.5.5.jar:2.5.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) [spring-boot-2.5.5.jar:2.5.5]
	at com.company.samplesales.SampleSalesJmixApplication.main(SampleSalesJmixApplication.java:16) [main/:na]
Caused by: java.lang.IllegalStateException: @Order on WebSecurityConfigurers must be unique. Order of 200 was already used on io.jmix.autoconfigure.securityoauth2.SecurityOAuth2AutoConfiguration$Oauth2AuthorizationServerConfiguration@55456711, so it cannot be used on io.jmix.autoconfigure.webdav.WebdavRestAutoConfiguration$DefaultWebdavRestBasicAuthConfiguration$$EnhancerBySpringCGLIB$$b982ced9@38c86702 too.
	at org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration.setFilterChainProxySecurityConfigurer(WebSecurityConfiguration.java:165) ~[spring-security-config-5.5.2.jar:5.5.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_301]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_301]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_301]
Caused by: java.lang.IllegalStateException: @Order on WebSecurityConfigurers must be unique. Order of 200 was already used on io.jmix.autoconfigure.securityoauth2.SecurityOAuth2AutoConfiguration$Oauth2AuthorizationServerConfiguration@55456711, so it cannot be used on io.jmix.autoconfigure.webdav.WebdavRestAutoConfiguration$DefaultWebdavRestBasicAuthConfiguration$$EnhancerBySpringCGLIB$$b982ced9@38c86702 too.

	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_301]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:725) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119) ~[spring-beans-5.3.10.jar:5.3.10]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.3.10.jar:5.3.10]
	... 17 common frames omitted
```
Exception occurs due WebDAV and REST add-on in the same project

**Comment by gorbunkov** [comment]
WebDAV basic authentication stopped working, because `WebdavRestSecurityConfiguration` must have a higher priority than `StandardSecurityConfiguration`. Probably the same issue is with `CognitoResourceServerConfiguration`.
