### ISSUE TITLE
An IllegalArgumentException error occurs when requesting the REST Entities API

### ISSUE THREAD

**Issue by Afanasevaa36** [Haulmont/jmix-rest#92]
**Description**
See [forum topic](https://forum.jmix.ru/t/oshibka-pri-vyzove-rest-entities-api/304)
**Steps to reproduce**
1. Add [project ](https://github.com/daring2/jmix-petclinic)
2. Run project
3. Log in 
4. Click Administration>Dynamic attributes>Create
5. Name: **Test** Entity type: **Pet Type** 
6. Create 
7. Name: **Test** Type: **String**
8. Ok>Ok
9. Click **Apply changes**
9. Open Postman
10. Send a request (POST) http://localhost:8080/oauth/token?grant_type=password&username=admin&password=admin
11. Send a request (GET) http://localhost:8080/rest/entities/petclinic_Pet?fetchPlan=browse
ER: Status: 200 ok
![Screenshot_12](https://user-images.githubusercontent.com/95623805/152994692-3993e6e8-9cb7-4e50-89b7-b3f35ecfc69e.png)
AR: Status 500 internal Server Eror
![Screenshot_13](https://user-images.githubusercontent.com/95623805/152995097-2f0ce9f7-cfe3-4978-9bbd-a391c4397d4f.png)
```
java.lang.IllegalArgumentException: Can't find getter for property '+testtest' at class io.jmix.petclinic.entity.pet.PetType
	at io.jmix.core.metamodel.model.utils.MethodsCache.getGetter(MethodsCache.java:179) ~[jmix-core-1.1.3.jar:na]
	at io.jmix.core.entity.BaseEntityEntry.getAttributeValue(BaseEntityEntry.java:85) ~[jmix-core-1.1.3.jar:na]
	at io.jmix.core.entity.EntityValues.getValue(EntityValues.java:100) ~[jmix-core-1.1.3.jar:na]
	at io.jmix.core.impl.serialization.EntitySerializationImpl$EntitySerializer.writeFields(EntitySerializationImpl.java:330) ~[jmix-core-1.1.3.jar:na]
	at io.jmix.core.impl.serialization.EntitySerializationImpl$EntitySerializer.serializeEntity(EntitySerializationImpl.java:246) ~[jmix-core-1.1.3.jar:na]
	at io.jmix.core.impl.serialization.EntitySerializationImpl$EntitySerializer.writeFields(EntitySerializationImpl.java:354) ~[jmix-core-1.1.3.jar:na]
	at io.jmix.core.impl.serialization.EntitySerializationImpl$EntitySerializer.serializeEntity(EntitySerializationImpl.java:246) ~[jmix-core-1.1.3.jar:na]
	at io.jmix.core.impl.serialization.EntitySerializationImpl$EntitySerializer.serialize(EntitySerializationImpl.java:219) ~[jmix-core-1.1.3.jar:na]
	at io.jmix.core.impl.serialization.EntitySerializationImpl$EntitySerializer.serialize(EntitySerializationImpl.java:187) ~[jmix-core-1.1.3.jar:na]
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81) ~[gson-2.8.9.jar:na]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[gson-2.8.9.jar:na]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97) ~[gson-2.8.9.jar:na]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61) ~[gson-2.8.9.jar:na]
	at com.google.gson.Gson.toJson(Gson.java:735) ~[gson-2.8.9.jar:na]
	at com.google.gson.Gson.toJson(Gson.java:714) ~[gson-2.8.9.jar:na]
	at com.google.gson.Gson.toJson(Gson.java:669) ~[gson-2.8.9.jar:na]
	at com.google.gson.Gson.toJson(Gson.java:649) ~[gson-2.8.9.jar:na]
	at io.jmix.core.impl.serialization.EntitySerializationImpl.toJson(EntitySerializationImpl.java:113) ~[jmix-core-1.1.3.jar:na]
	at io.jmix.rest.impl.service.EntitiesControllerManager._loadEntitiesList(EntitiesControllerManager.java:342) ~[jmix-rest-1.1.1.jar:na]
	at io.jmix.rest.impl.service.EntitiesControllerManager.loadEntitiesList(EntitiesControllerManager.java:164) ~[jmix-rest-1.1.1.jar:na]

```

**Comment by Afanasevaa36** [comment]
Jmix version: 1.3.999-SNAPSHOT - verified
